grafana:
  adminUser: admin
  adminPassword: "CHANGE_ME_IN_PRODUCTION"
  service:
    type: ClusterIP
  # Disable anonymous access
  auth:
    anonymous:
      enabled: false
    basic:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 2Gi
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
