grafana:
  adminUser: admin
  adminPassword: admin            # OK en labo local uniquement
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 2Gi
    # Par défaut, ce chart sélectionne les ServiceMonitor portant le label "release: <nom_release>"
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
